# fly.toml app configuration file generated for bagstash0 on 2024-01-03T02:28:34+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bagstash0"
primary_region = "cdg"

[build]
  image = "civa41/e-commerce-store:latest"

  [env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51OTCUGHmuL0YqumfgvbG4Z0boXpvcrPZSnvysNs4OKJM3eCIWYioF4eXjlrowWlYQw32i1VxzMneBDKs29IXLGNX005a5hF23z"
  Cloudinary__CloudName= "dbt6rcfiq"
  Cloudinary__ApiKey = "749418578375265"
  Cloudinary__ApiSecret =  "Ht0bUIENUHh3gCa1ka0pqJ1c4bM"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
